name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Build Docusaurus site
      run: yarn build

    - name: Upload files via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/**"
        strip_components: 1
        target: "/var/www/docs.datashelter.tech"
